DECLARE
  STR VARCHAR(10):='&STR';
  STRCPY VARCHAR(10):=STR;
  REVSTR VARCHAR(10);
  L NUMBER;
  I NUMBER;
BEGIN
  L:=LENGTH(STR);
  REVSTR:='';
  /*DBMS_OUTPUT.PUT_LINE('LENGTH IS '||L);*/
  FOR I IN REVERSE 1..L
  LOOP
    REVSTR:=REVSTR||SUBSTR(STR,I,1);
  END LOOP;
  IF STR=REVSTR THEN
    DBMS_OUTPUT.PUT_LINE('THE STRING "'||STR||'" IS PALINDROME');
  ELSE
    DBMS_OUTPUT.PUT_LINE('THE STRING "'||STR||'" IS NOT PALINDROME');
  END IF;
END;